name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and run deploy script
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_IP }}
          username: azureuser
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser/stage6
            ./deploy.sh
